version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: statemachine_postgres
    environment:
      POSTGRES_USER: statemachine_user
      POSTGRES_PASSWORD: statemachine_pass
      POSTGRES_DB: statemachine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
