version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: statemachine_postgres
    environment:
      POSTGRES_USER: statemachine_user
      POSTGRES_PASSWORD: statemachine_pass
      POSTGRES_DB: statemachine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  postgres_data:
